name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements-dev.txt ]; then pip install -r api/requirements-dev.txt; fi
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
          
      - name: Lint with ruff
        run: |
          if command -v ruff &> /dev/null; then
            ruff check api/
          fi
          
      - name: Check formatting with black
        run: |
          if command -v black &> /dev/null; then
            black --check api/
          fi
          
      - name: Check imports with isort
        run: |
          if command -v isort &> /dev/null; then
            isort --check-only --profile black api/
          fi
          
      - name: Test with pytest
        run: |
          if [ -d api/tests ]; then
            pytest api/tests/
          fi

  spa-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: ./spa
        run: |
          if [ -f package.json ]; then
            npm ci
          fi
          
      - name: Lint with ESLint
        working-directory: ./spa
        run: |
          if [ -f package.json ] && grep -q "eslint" package.json; then
            npm run lint
          fi
          
      - name: Check formatting with Prettier
        working-directory: ./spa
        run: |
          if [ -f package.json ] && grep -q "prettier" package.json; then
            npm run format:check
          fi
